# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ControlWindow.ui'
#
# Created: Tue Oct 27 14:50:17 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ControlWindow(object):
    def setupUi(self, ControlWindow):
        ControlWindow.setObjectName(_fromUtf8("ControlWindow"))
        ControlWindow.resize(396, 661)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ControlWindow.sizePolicy().hasHeightForWidth())
        ControlWindow.setSizePolicy(sizePolicy)
        ControlWindow.setMinimumSize(QtCore.QSize(300, 661))
        ControlWindow.setMaximumSize(QtCore.QSize(396, 661))
        ControlWindow.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.centralwidget = QtGui.QWidget(ControlWindow)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout_15 = QtGui.QVBoxLayout()
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.slingSize_label = QtGui.QLabel(self.centralwidget)
        self.slingSize_label.setObjectName(_fromUtf8("slingSize_label"))
        self.verticalLayout_2.addWidget(self.slingSize_label)
        self.slingSize_spinBox = QtGui.QSpinBox(self.centralwidget)
        self.slingSize_spinBox.setAccelerated(False)
        self.slingSize_spinBox.setMinimum(1)
        self.slingSize_spinBox.setMaximum(1000)
        self.slingSize_spinBox.setProperty("value", 50)
        self.slingSize_spinBox.setObjectName(_fromUtf8("slingSize_spinBox"))
        self.verticalLayout_2.addWidget(self.slingSize_spinBox)
        self.verticalLayout_15.addLayout(self.verticalLayout_2)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.centerSize_label = QtGui.QLabel(self.centralwidget)
        self.centerSize_label.setObjectName(_fromUtf8("centerSize_label"))
        self.verticalLayout_7.addWidget(self.centerSize_label)
        self.centerSize_spinBox = QtGui.QSpinBox(self.centralwidget)
        self.centerSize_spinBox.setMinimum(1)
        self.centerSize_spinBox.setMaximum(1000)
        self.centerSize_spinBox.setProperty("value", 25)
        self.centerSize_spinBox.setObjectName(_fromUtf8("centerSize_spinBox"))
        self.verticalLayout_7.addWidget(self.centerSize_spinBox)
        self.verticalLayout_15.addLayout(self.verticalLayout_7)
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.radius_label = QtGui.QLabel(self.centralwidget)
        self.radius_label.setObjectName(_fromUtf8("radius_label"))
        self.verticalLayout_14.addWidget(self.radius_label)
        self.radius_spinBox = QtGui.QSpinBox(self.centralwidget)
        self.radius_spinBox.setMinimum(1)
        self.radius_spinBox.setMaximum(1000)
        self.radius_spinBox.setProperty("value", 100)
        self.radius_spinBox.setObjectName(_fromUtf8("radius_spinBox"))
        self.verticalLayout_14.addWidget(self.radius_spinBox)
        self.verticalLayout_15.addLayout(self.verticalLayout_14)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.thickness_label = QtGui.QLabel(self.centralwidget)
        self.thickness_label.setObjectName(_fromUtf8("thickness_label"))
        self.verticalLayout_9.addWidget(self.thickness_label)
        self.thickness_spinBox = QtGui.QSpinBox(self.centralwidget)
        self.thickness_spinBox.setMinimum(1)
        self.thickness_spinBox.setMaximum(1000)
        self.thickness_spinBox.setObjectName(_fromUtf8("thickness_spinBox"))
        self.verticalLayout_9.addWidget(self.thickness_spinBox)
        self.verticalLayout_15.addLayout(self.verticalLayout_9)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.aVelocity_label = QtGui.QLabel(self.centralwidget)
        self.aVelocity_label.setObjectName(_fromUtf8("aVelocity_label"))
        self.verticalLayout_3.addWidget(self.aVelocity_label)
        self.aVelocity_doubleSpinBox = QtGui.QDoubleSpinBox(self.centralwidget)
        self.aVelocity_doubleSpinBox.setDecimals(3)
        self.aVelocity_doubleSpinBox.setMaximum(100.0)
        self.aVelocity_doubleSpinBox.setSingleStep(0.01)
        self.aVelocity_doubleSpinBox.setProperty("value", 0.01)
        self.aVelocity_doubleSpinBox.setObjectName(_fromUtf8("aVelocity_doubleSpinBox"))
        self.verticalLayout_3.addWidget(self.aVelocity_doubleSpinBox)
        self.verticalLayout_15.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.distance_label = QtGui.QLabel(self.centralwidget)
        self.distance_label.setObjectName(_fromUtf8("distance_label"))
        self.verticalLayout_4.addWidget(self.distance_label)
        self.distance_doubleSpinBox = QtGui.QDoubleSpinBox(self.centralwidget)
        self.distance_doubleSpinBox.setDecimals(1)
        self.distance_doubleSpinBox.setMaximum(1000.0)
        self.distance_doubleSpinBox.setProperty("value", 100.0)
        self.distance_doubleSpinBox.setObjectName(_fromUtf8("distance_doubleSpinBox"))
        self.verticalLayout_4.addWidget(self.distance_doubleSpinBox)
        self.verticalLayout_15.addLayout(self.verticalLayout_4)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.diameter_label = QtGui.QLabel(self.centralwidget)
        self.diameter_label.setObjectName(_fromUtf8("diameter_label"))
        self.verticalLayout_6.addWidget(self.diameter_label)
        self.diameter_doubleSpinBox = QtGui.QDoubleSpinBox(self.centralwidget)
        self.diameter_doubleSpinBox.setDecimals(1)
        self.diameter_doubleSpinBox.setMaximum(1000.0)
        self.diameter_doubleSpinBox.setProperty("value", 10.0)
        self.diameter_doubleSpinBox.setObjectName(_fromUtf8("diameter_doubleSpinBox"))
        self.verticalLayout_6.addWidget(self.diameter_doubleSpinBox)
        self.verticalLayout_15.addLayout(self.verticalLayout_6)
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.density_label = QtGui.QLabel(self.centralwidget)
        self.density_label.setObjectName(_fromUtf8("density_label"))
        self.verticalLayout_10.addWidget(self.density_label)
        self.density_doubleSpinBox = QtGui.QDoubleSpinBox(self.centralwidget)
        self.density_doubleSpinBox.setDecimals(3)
        self.density_doubleSpinBox.setMaximum(100.0)
        self.density_doubleSpinBox.setObjectName(_fromUtf8("density_doubleSpinBox"))
        self.verticalLayout_10.addWidget(self.density_doubleSpinBox)
        self.verticalLayout_15.addLayout(self.verticalLayout_10)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.viscosity_label = QtGui.QLabel(self.centralwidget)
        self.viscosity_label.setObjectName(_fromUtf8("viscosity_label"))
        self.verticalLayout.addWidget(self.viscosity_label)
        self.viscosity_doubleSpinBox = QtGui.QDoubleSpinBox(self.centralwidget)
        self.viscosity_doubleSpinBox.setDecimals(5)
        self.viscosity_doubleSpinBox.setMaximum(1000000.0)
        self.viscosity_doubleSpinBox.setObjectName(_fromUtf8("viscosity_doubleSpinBox"))
        self.verticalLayout.addWidget(self.viscosity_doubleSpinBox)
        self.verticalLayout_15.addLayout(self.verticalLayout)
        self.gridLayout.addLayout(self.verticalLayout_15, 0, 0, 1, 1)
        self.verticalLayout_16 = QtGui.QVBoxLayout()
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.filled_checkBox = QtGui.QCheckBox(self.centralwidget)
        self.filled_checkBox.setChecked(True)
        self.filled_checkBox.setObjectName(_fromUtf8("filled_checkBox"))
        self.verticalLayout_16.addWidget(self.filled_checkBox)
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.lVelocity_label = QtGui.QLabel(self.centralwidget)
        self.lVelocity_label.setObjectName(_fromUtf8("lVelocity_label"))
        self.verticalLayout_5.addWidget(self.lVelocity_label)
        self.lVelocity_LCDNumber = QtGui.QLCDNumber(self.centralwidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(33, 33, 33))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 100, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(33, 33, 33))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(33, 33, 33))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(33, 33, 33))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 100, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(33, 33, 33))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(33, 33, 33))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 100, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.lVelocity_LCDNumber.setPalette(palette)
        self.lVelocity_LCDNumber.setFrameShape(QtGui.QFrame.NoFrame)
        self.lVelocity_LCDNumber.setFrameShadow(QtGui.QFrame.Raised)
        self.lVelocity_LCDNumber.setSmallDecimalPoint(False)
        self.lVelocity_LCDNumber.setNumDigits(6)
        self.lVelocity_LCDNumber.setObjectName(_fromUtf8("lVelocity_LCDNumber"))
        self.verticalLayout_5.addWidget(self.lVelocity_LCDNumber)
        self.verticalLayout_12.addLayout(self.verticalLayout_5)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.DEPForce_label = QtGui.QLabel(self.centralwidget)
        self.DEPForce_label.setTextFormat(QtCore.Qt.PlainText)
        self.DEPForce_label.setObjectName(_fromUtf8("DEPForce_label"))
        self.verticalLayout_8.addWidget(self.DEPForce_label)
        self.DEPForce_LCDNumber = QtGui.QLCDNumber(self.centralwidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(33, 33, 33))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 100, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(33, 33, 33))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(33, 33, 33))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(33, 33, 33))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 100, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(33, 33, 33))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(33, 33, 33))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 100, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.DEPForce_LCDNumber.setPalette(palette)
        self.DEPForce_LCDNumber.setFrameShape(QtGui.QFrame.NoFrame)
        self.DEPForce_LCDNumber.setFrameShadow(QtGui.QFrame.Raised)
        self.DEPForce_LCDNumber.setSmallDecimalPoint(False)
        self.DEPForce_LCDNumber.setNumDigits(6)
        self.DEPForce_LCDNumber.setObjectName(_fromUtf8("DEPForce_LCDNumber"))
        self.verticalLayout_8.addWidget(self.DEPForce_LCDNumber)
        self.verticalLayout_12.addLayout(self.verticalLayout_8)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.cForce_label = QtGui.QLabel(self.centralwidget)
        self.cForce_label.setTextFormat(QtCore.Qt.PlainText)
        self.cForce_label.setObjectName(_fromUtf8("cForce_label"))
        self.verticalLayout_11.addWidget(self.cForce_label)
        self.cForce_LCDNumber = QtGui.QLCDNumber(self.centralwidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(33, 33, 33))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 100, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(33, 33, 33))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(33, 33, 33))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(33, 33, 33))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 100, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(33, 33, 33))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(33, 33, 33))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(100, 100, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.cForce_LCDNumber.setPalette(palette)
        self.cForce_LCDNumber.setFrameShape(QtGui.QFrame.NoFrame)
        self.cForce_LCDNumber.setFrameShadow(QtGui.QFrame.Raised)
        self.cForce_LCDNumber.setSmallDecimalPoint(False)
        self.cForce_LCDNumber.setNumDigits(6)
        self.cForce_LCDNumber.setObjectName(_fromUtf8("cForce_LCDNumber"))
        self.verticalLayout_11.addWidget(self.cForce_LCDNumber)
        self.verticalLayout_12.addLayout(self.verticalLayout_11)
        self.verticalLayout_16.addLayout(self.verticalLayout_12)
        self.gridLayout.addLayout(self.verticalLayout_16, 0, 1, 1, 1)
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.engage_pushButton = QtGui.QPushButton(self.centralwidget)
        self.engage_pushButton.setObjectName(_fromUtf8("engage_pushButton"))
        self.horizontalLayout.addWidget(self.engage_pushButton)
        self.stop_pushButton = QtGui.QPushButton(self.centralwidget)
        self.stop_pushButton.setObjectName(_fromUtf8("stop_pushButton"))
        self.horizontalLayout.addWidget(self.stop_pushButton)
        self.verticalLayout_13.addLayout(self.horizontalLayout)
        self.record_pushButton = QtGui.QPushButton(self.centralwidget)
        self.record_pushButton.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.record_pushButton.setObjectName(_fromUtf8("record_pushButton"))
        self.verticalLayout_13.addWidget(self.record_pushButton)
        self.gridLayout.addLayout(self.verticalLayout_13, 1, 0, 1, 2)
        spacerItem = QtGui.QSpacerItem(20, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 2, 1, 1, 1)
        ControlWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(ControlWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 396, 27))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuColor = QtGui.QMenu(self.menubar)
        self.menuColor.setObjectName(_fromUtf8("menuColor"))
        ControlWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(ControlWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        ControlWindow.setStatusBar(self.statusbar)
        self.action_quit = QtGui.QAction(ControlWindow)
        self.action_quit.setObjectName(_fromUtf8("action_quit"))
        self.action_invert = QtGui.QAction(ControlWindow)
        self.action_invert.setCheckable(True)
        self.action_invert.setObjectName(_fromUtf8("action_invert"))
        self.actionReset = QtGui.QAction(ControlWindow)
        self.actionReset.setObjectName(_fromUtf8("actionReset"))
        self.menuFile.addAction(self.action_quit)
        self.menuColor.addAction(self.action_invert)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuColor.menuAction())
        self.slingSize_label.setBuddy(self.slingSize_spinBox)
        self.centerSize_label.setBuddy(self.centerSize_spinBox)
        self.radius_label.setBuddy(self.centerSize_spinBox)
        self.thickness_label.setBuddy(self.thickness_spinBox)
        self.aVelocity_label.setBuddy(self.aVelocity_doubleSpinBox)
        self.distance_label.setBuddy(self.distance_doubleSpinBox)
        self.diameter_label.setBuddy(self.diameter_doubleSpinBox)
        self.density_label.setBuddy(self.density_doubleSpinBox)
        self.viscosity_label.setBuddy(self.viscosity_doubleSpinBox)

        self.retranslateUi(ControlWindow)
        QtCore.QObject.connect(self.action_quit, QtCore.SIGNAL(_fromUtf8("activated()")), ControlWindow.close)
        QtCore.QMetaObject.connectSlotsByName(ControlWindow)
        ControlWindow.setTabOrder(self.slingSize_spinBox, self.centerSize_spinBox)
        ControlWindow.setTabOrder(self.centerSize_spinBox, self.thickness_spinBox)
        ControlWindow.setTabOrder(self.thickness_spinBox, self.aVelocity_doubleSpinBox)
        ControlWindow.setTabOrder(self.aVelocity_doubleSpinBox, self.distance_doubleSpinBox)
        ControlWindow.setTabOrder(self.distance_doubleSpinBox, self.diameter_doubleSpinBox)
        ControlWindow.setTabOrder(self.diameter_doubleSpinBox, self.density_doubleSpinBox)
        ControlWindow.setTabOrder(self.density_doubleSpinBox, self.viscosity_doubleSpinBox)
        ControlWindow.setTabOrder(self.viscosity_doubleSpinBox, self.engage_pushButton)
        ControlWindow.setTabOrder(self.engage_pushButton, self.stop_pushButton)
        ControlWindow.setTabOrder(self.stop_pushButton, self.record_pushButton)

    def retranslateUi(self, ControlWindow):
        ControlWindow.setWindowTitle(_translate("ControlWindow", "Control Window (sling)", None))
        self.slingSize_label.setText(_translate("ControlWindow", "&Sling size", None))
        self.slingSize_spinBox.setToolTip(_translate("ControlWindow", "Scale of the figure", None))
        self.centerSize_label.setText(_translate("ControlWindow", "&Center size", None))
        self.radius_label.setText(_translate("ControlWindow", "&Radius", None))
        self.thickness_label.setText(_translate("ControlWindow", "&Thickness", None))
        self.thickness_spinBox.setToolTip(_translate("ControlWindow", "Thickness of the lines", None))
        self.aVelocity_label.setText(_translate("ControlWindow", "&Angular velocity (rps)", None))
        self.aVelocity_doubleSpinBox.setToolTip(_translate("ControlWindow", "Angular velocity in revolutions per second", None))
        self.distance_label.setText(_translate("ControlWindow", "&Distance (um)", None))
        self.distance_doubleSpinBox.setToolTip(_translate("ControlWindow", "The distance from the center of the wheel to the center of the bead", None))
        self.diameter_label.setText(_translate("ControlWindow", "Bead dia&meter (um)", None))
        self.diameter_doubleSpinBox.setToolTip(_translate("ControlWindow", "Radius of the bead in microns", None))
        self.density_label.setText(_translate("ControlWindow", "Bead de&nsity (g/cm3)", None))
        self.density_doubleSpinBox.setToolTip(_translate("ControlWindow", "The density of the bead in g/cm3", None))
        self.viscosity_label.setText(_translate("ControlWindow", "Dynamic &viscosity (mPa s)", None))
        self.viscosity_doubleSpinBox.setToolTip(_translate("ControlWindow", "Dynamic viscosity of the solution in mPa s", None))
        self.filled_checkBox.setText(_translate("ControlWindow", "Filled", None))
        self.lVelocity_label.setText(_translate("ControlWindow", "Linear velocity (um/s)", None))
        self.lVelocity_LCDNumber.setToolTip(_translate("ControlWindow", "Linear velocity of the bead in microns per second", None))
        self.DEPForce_label.setText(_translate("ControlWindow", "DEP (pN)", None))
        self.DEPForce_LCDNumber.setToolTip(_translate("ControlWindow", "Dielectrophoretic force in pN", None))
        self.cForce_label.setText(_translate("ControlWindow", "Centripetal force (pN)", None))
        self.cForce_LCDNumber.setToolTip(_translate("ControlWindow", "Centripetal force in pN", None))
        self.engage_pushButton.setToolTip(_translate("ControlWindow", "Start the animation", None))
        self.engage_pushButton.setText(_translate("ControlWindow", "&Engage", None))
        self.stop_pushButton.setToolTip(_translate("ControlWindow", "Stop the animation", None))
        self.stop_pushButton.setText(_translate("ControlWindow", "Sto&p", None))
        self.record_pushButton.setToolTip(_translate("ControlWindow", "Record the current parameters to file", None))
        self.record_pushButton.setText(_translate("ControlWindow", "&Record", None))
        self.menuFile.setTitle(_translate("ControlWindow", "File", None))
        self.menuColor.setTitle(_translate("ControlWindow", "Tools", None))
        self.action_quit.setText(_translate("ControlWindow", "Quit", None))
        self.action_quit.setShortcut(_translate("ControlWindow", "Ctrl+Q", None))
        self.action_invert.setText(_translate("ControlWindow", "Invert", None))
        self.action_invert.setShortcut(_translate("ControlWindow", "Alt+I", None))
        self.actionReset.setText(_translate("ControlWindow", "Reset", None))

